# Generated by Django 2.2.2 on 2019-07-01 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=254, null=True)),
                ('enabled', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='StockTNX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=5, max_digits=17)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='stocktnx',
            index=models.Index(fields=['user', 'stock'], name='market_stoc_user_id_709c6c_idx'),
        ),
    ]
