const _PREFIX = 'portfolio__';

const INITIALIZE = _PREFIX + 'INITIALIZE';
const SET_OPTION = _PREFIX + 'OPTION_CHANGE';

const SET_TMP_TRACKING = _PREFIX + 'SET_TMP_TRACKING';
const UNSET_TMP_TRACKING = _PREFIX + 'UNSET_TMP_TRACKING';
const UPDATE_STOCK_LAST_PRICE = _PREFIX + 'UPDATE_STOCK_LAST_PRICE';
const UPDATE_STOCK_OHLC = _PREFIX + 'UPDATE_STOCK_OHLC';

const START_ACTION_BUY = _PREFIX + 'START_ACTION_BUY';
const STOP_ACTION_BUY = _PREFIX + 'STOP_ACTION_BUY';

export default {
    INITIALIZE,
    SET_OPTION,
    SET_TMP_TRACKING,
    UNSET_TMP_TRACKING,
    UPDATE_STOCK_LAST_PRICE,
    UPDATE_STOCK_OHLC,
    START_ACTION_BUY,
    STOP_ACTION_BUY,
}